services:
  database:
    container_name: CollabDraw
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - collabdraw-network

  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    container_name: frontend
    ports: [3000:3000]
    env_file: .env
    depends_on: [database]
    networks: [collabdraw-network]

  ws:
    build:
      context: .
      dockerfile: ./docker/ws.dockerfile
    container_name: server
    ports: [8080:8080]
    env_file: .env
    depends_on: [database]
    networks: [collabdraw-network]

volumes:
  db_data:

networks:
  collabdraw-network:
