services:
  database:
    container_name: CollabDraw
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - collabdraw-network

volumes:
  db_data:

networks:
  collabdraw-network:
    name: collabdraw-network
    driver: bridge
